import type { TimelineMetadata } from "../types/TimelineTypes.js";

export type MessageType =
  | "speak"
  | "warn"
  | "block"
  | "observe"
  | "system"
  | "sms"
  | "call_transcript";

/**
 * Metadata keys understood by the built-in phone plugin.
 * Any other key is preserved but ignored by the engine.
 */
export interface PhoneMessageMetadata {
  channel?: "sms" | "call";
  callId?: string;
  fromNumber?: string;
  toNumber?: string;
  participants?: string[];
  /** True for synthetic messages generated by the engine (e.g. "[chiamata in arrivo]"). */
  system?: boolean;
}

/**
 * Metadata populated by the federation layer when a message either
 * originates from a remote world (inbound) or is being routed to one
 * (outbound, set by the agent tool before publishing). Any other key is
 * preserved but ignored by the engine.
 */
export interface FederationMessageMetadata {
  /** Set on inbound messages: the originating world id. */
  sourceWorld?: string;
  /** Set on inbound messages: the federation envelope id. */
  federationEnvelopeId?: string;
  /** Set on outbound messages by `send_cross_world_message` to choose the wire channel. */
  federationChannel?: "sms" | "email" | "call_request" | "call_turn" | "system";
  /** Optional correlation id for multi-turn cross-world conversations. */
  federationCorrelationId?: string;
}

/**
 * Metadata carried from an agent action into the routed message.
 * Integrators may add opaque correlation fields; WorldSim preserves them
 * without assigning application-specific semantics.
 */
export type MessageMetadata =
  & Record<string, unknown>
  & PhoneMessageMetadata
  & FederationMessageMetadata
  & TimelineMetadata;

export interface Message {
  id: string;
  from: string;
  to: string | "*";
  type: MessageType;
  content: string;
  tick: number;
  metadata?: MessageMetadata | undefined;
}

export type MessageRouteKind =
  | "conversation"
  | "neighborhood"
  | "proximity"
  | "perception"
  | "broadcast"
  | "dropped";

/**
 * Immutable routing outcome emitted after WorldSim has delivered (or dropped)
 * a message. Broadcasts use `"*"` because their effective audience is resolved
 * by subscribers rather than enumerated by the router.
 */
export interface MessageDeliveryReceipt {
  messageId: string;
  from: string;
  recipients: readonly string[] | "*";
  route: MessageRouteKind;
  tick: number;
  metadata?: MessageMetadata | undefined;
  reason?: string | undefined;
}
