export type MessageType =
  | "speak"
  | "warn"
  | "block"
  | "observe"
  | "system"
  | "sms"
  | "call_transcript";

/**
 * Metadata keys understood by the built-in phone plugin.
 * Any other key is preserved but ignored by the engine.
 */
export interface PhoneMessageMetadata {
  channel?: "sms" | "call";
  callId?: string;
  fromNumber?: string;
  toNumber?: string;
  participants?: string[];
  /** True for synthetic messages generated by the engine (e.g. "[chiamata in arrivo]"). */
  system?: boolean;
}

export interface Message {
  id: string;
  from: string;
  to: string | "*";
  type: MessageType;
  content: string;
  tick: number;
  metadata?: (Record<string, unknown> & PhoneMessageMetadata);
}
